# Generated by Django 5.2.7 on 2025-11-02 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default='CHARON', help_text='Name of the ship/station AI system', max_length=100),
        ),
        migrations.CreateModel(
            name='ActiveView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_slug', models.CharField(blank=True, help_text='Directory name under data/locations/', max_length=200)),
                ('view_type', models.CharField(choices=[('MESSAGES', 'Broadcast Messages'), ('COMM_TERMINAL', 'Communications Terminal'), ('ENCOUNTER_MAP', 'Encounter Map'), ('SHIP_DASHBOARD', 'Ship Dashboard')], default='MESSAGES', help_text='Type of view to display', max_length=50)),
                ('view_slug', models.CharField(blank=True, help_text='Specific terminal/map slug (e.g., commanders_terminal)', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Active Display View',
                'verbose_name_plural': 'Active Display View',
            },
        ),
    ]
