# Generated by Django 5.2.7 on 2025-11-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_alter_message_sender_activeview'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='overlay_location_slug',
            field=models.CharField(blank=True, help_text='Location of terminal to overlay on main view', max_length=200),
        ),
        migrations.AddField(
            model_name='activeview',
            name='overlay_terminal_slug',
            field=models.CharField(blank=True, help_text='Terminal slug to show as overlay', max_length=200),
        ),
    ]
