# Generated by Django 5.2.7 on 2025-11-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_activeview_overlay_location_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeview',
            name='view_type',
            field=models.CharField(choices=[('MESSAGES', 'Broadcast Messages'), ('COMM_TERMINAL', 'Communications Terminal'), ('ENCOUNTER_MAP', 'Encounter Map'), ('SHIP_DASHBOARD', 'Ship Dashboard'), ('STANDBY', 'Standby Screen')], default='MESSAGES', help_text='Type of view to display', max_length=50),
        ),
    ]
