# Generated by Django 5.2.7 on 2025-11-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_alter_activeview_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeview',
            name='view_type',
            field=models.CharField(choices=[('STANDBY', 'Standby Screen'), ('CAMPAIGN_DASHBOARD', 'Campaign Dashboard'), ('ENCOUNTER_MAP', 'Encounter Map'), ('COMM_TERMINAL', 'Communications Terminal'), ('MESSAGES', 'Broadcast Messages'), ('SHIP_DASHBOARD', 'Ship Dashboard')], default='STANDBY', help_text='Type of view to display', max_length=50),
        ),
    ]
