# Generated by Django 5.2.7 on 2025-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_alter_activeview_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='charon_mode',
            field=models.CharField(choices=[('DISPLAY', 'Display Only'), ('QUERY', 'Query Mode')], default='DISPLAY', help_text='CHARON terminal interaction mode', max_length=20),
        ),
        migrations.AlterField(
            model_name='activeview',
            name='view_type',
            field=models.CharField(choices=[('STANDBY', 'Standby Screen'), ('CAMPAIGN_DASHBOARD', 'Campaign Dashboard'), ('ENCOUNTER_MAP', 'Encounter Map'), ('COMM_TERMINAL', 'Communications Terminal'), ('MESSAGES', 'Broadcast Messages'), ('SHIP_DASHBOARD', 'Ship Dashboard'), ('CHARON_TERMINAL', 'CHARON Interactive Terminal')], default='STANDBY', help_text='Type of view to display', max_length=50),
        ),
    ]
