# Generated by Django 5.2.7 on 2025-12-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_add_charon_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='charon_location_path',
            field=models.CharField(blank=True, help_text='Path to active CHARON instance (e.g., "tau-ceti/tau-ceti-f/verdant-base")', max_length=500),
        ),
    ]
