# Generated by Django 5.2.7 on 2025-12-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_add_charon_location_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='charon_dialog_open',
            field=models.BooleanField(default=False, help_text='Whether the CHARON dialog overlay is visible to players'),
        ),
    ]
