# Generated by Django 5.2.7 on 2025-12-31 05:19

from django.db import migrations, models


def rename_campaign_dashboard_to_bridge(apps, schema_editor):
    """Update any existing records from CAMPAIGN_DASHBOARD to BRIDGE."""
    ActiveView = apps.get_model('terminal', 'ActiveView')
    ActiveView.objects.filter(view_type='CAMPAIGN_DASHBOARD').update(view_type='BRIDGE')


def rename_bridge_to_campaign_dashboard(apps, schema_editor):
    """Reverse: Update records from BRIDGE back to CAMPAIGN_DASHBOARD."""
    ActiveView = apps.get_model('terminal', 'ActiveView')
    ActiveView.objects.filter(view_type='BRIDGE').update(view_type='CAMPAIGN_DASHBOARD')


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_add_charon_dialog_open'),
    ]

    operations = [
        # First update existing data
        migrations.RunPython(rename_campaign_dashboard_to_bridge, rename_bridge_to_campaign_dashboard),
        # Then alter the field choices
        migrations.AlterField(
            model_name='activeview',
            name='view_type',
            field=models.CharField(choices=[('STANDBY', 'Standby Screen'), ('BRIDGE', 'Bridge'), ('ENCOUNTER_MAP', 'Encounter Map'), ('COMM_TERMINAL', 'Communications Terminal'), ('MESSAGES', 'Broadcast Messages'), ('SHIP_DASHBOARD', 'Ship Dashboard'), ('CHARON_TERMINAL', 'CHARON Interactive Terminal')], default='STANDBY', help_text='Type of view to display', max_length=50),
        ),
    ]
