# Generated by Django 5.2.7 on 2025-12-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0009_rename_campaign_dashboard_to_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeview',
            name='view_type',
            field=models.CharField(choices=[('STANDBY', 'Standby Screen'), ('BRIDGE', 'Bridge'), ('ENCOUNTER', 'Encounter Display'), ('COMM_TERMINAL', 'Communications Terminal'), ('MESSAGES', 'Broadcast Messages'), ('SHIP_DASHBOARD', 'Ship Dashboard'), ('CHARON_TERMINAL', 'CHARON Interactive Terminal')], default='STANDBY', help_text='Type of view to display', max_length=50),
        ),
    ]
