# Generated by Django 5.2.7 on 2026-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0010_alter_activeview_view_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='encounter_deck_id',
            field=models.CharField(blank=True, help_text='ID of current deck (e.g., "deck_1")', max_length=100),
        ),
        migrations.AddField(
            model_name='activeview',
            name='encounter_level',
            field=models.IntegerField(default=1, help_text='Current deck/level being displayed (1-indexed)'),
        ),
        migrations.AddField(
            model_name='activeview',
            name='encounter_room_visibility',
            field=models.JSONField(blank=True, default=dict, help_text='Map of room_id -> visible (bool) for GM-controlled visibility'),
        ),
    ]
