# Generated by Django 5.2.7 on 2026-01-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0011_add_encounter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='encounter_door_status',
            field=models.JSONField(blank=True, default=dict, help_text='Map of connection_id -> door_status string (runtime override)'),
        ),
    ]
