# Generated by Django 5.2.7 on 2026-02-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0012_activeview_encounter_door_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='charon_active_channel',
            field=models.CharField(default='story', help_text='Active CHARON channel (story, bridge, encounter-{slug})', max_length=200),
        ),
    ]
