# Generated by Django 5.2.7 on 2026-02-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0013_activeview_charon_active_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='ship_system_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Runtime overrides for ship system states {system_name: {status, condition, info}}'),
        ),
    ]
