# Generated by Django 5.2.7 on 2026-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0014_activeview_ship_system_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='encounter_tokens',
            field=models.JSONField(blank=True, default=dict, help_text='Map of token_id -> token data for encounter tokens'),
        ),
    ]
