# Generated by Django 5.2.7 on 2026-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0015_activeview_encounter_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeview',
            name='encounter_active_portraits',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of NPC IDs currently displayed as portrait overlays'),
        ),
    ]
